services:
    pmi:
        image: texlive/texlive:latest
        working_dir: /workdir
        #user: 1000:1000
        #command: "xelatex -interaction=nonstopmode  -output-directory=/out ${MY_FILE}"
        command: pdflatex ${MY_FILE}
        #command: id -u
        volumes:
            - ./src/:/workdir/
            - ./out/:/out/